### ISSUE TITLE
class thunderbird

### ISSUE THREAD

**Issue by Arash-SJPI22** [iguanajuice/sway-font-awesome#11]
Icon suggestion: "fa-solid fa-envelopes-bulk"

**Comment by iguanajuice** [comment]
Nerd fonts have an actual thunderbird icon; I think I'll be using that instead.

**Comment by iguanajuice** [comment]
Added the icon: https://github.com/iguanajuice/sway-font-awesome/commit/19da68984c152faaceb851855b78d0465425aa42

If the icon is too big or too small, let me know with screenshots.
