### ISSUE TITLE
Config will fail when using a version of sway without xwayland support

### ISSUE THREAD

**Issue by El-Virus** [iguanajuice/sway-font-awesome#18]
As explained [in the sway repo](https://github.com/swaywm/sway/issues/3653), using the `class=` criteria when xwayland support has not been enabled will cause sway to complain about the invalidity of the configuration.

**Comment by iguanajuice** [comment]
Resolved. b9a739dc452da113e618b898155c26fcb1f047fa b2bee221e25452d46e93262870c7c75f6321cb35
